from __future__ import annotations

import re
from typing import Any

from fastapi import FastAPI, HTTPException, Response
from fastapi.middleware.cors import CORSMiddleware


app = FastAPI(title="Tradecraft NinjaScript Export API")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["POST", "OPTIONS"],
    allow_headers=["*"],
)


@app.post("/api/export_ninjascript")
def export_ninjascript(payload: dict[str, Any]) -> Response:
    strategy = payload.get("strategy")
    if not isinstance(strategy, dict):
        raise HTTPException(status_code=422, detail="Request body must include a strategy object.")

    class_name = safe_class_name(strategy.get("name", "TradecraftStrategy"))
    source = render_ninjascript(class_name, strategy)
    return Response(
        content=source,
        media_type="text/x-csharp",
        headers={
            "Content-Disposition": f'attachment; filename="{class_name}.cs"'
        },
    )


def safe_class_name(name: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9_]+", "_", str(name)).strip("_")
    if not cleaned:
        cleaned = "TradecraftStrategy"
    if cleaned[0].isdigit():
        cleaned = f"Strategy_{cleaned}"
    return cleaned


def render_ninjascript(class_name: str, strategy: dict[str, Any]) -> str:
    entry_comment = rule_comment(strategy.get("entry"))
    exit_comment = rule_comment(strategy.get("exit"))
    symbol = strategy.get("symbol", "UNKNOWN")
    timeframe = strategy.get("timeframe", "1D")
    initial_capital = strategy.get("risk", {}).get("initialCapital", 100000)
    position_size = strategy.get("risk", {}).get("positionSizePct", 100)

    return f"""// Auto-generated by Tradecraft Backtesting Engine.
// Source strategy: {strategy.get("name", class_name)}
// Symbol/timeframe: {symbol} / {timeframe}
// Initial capital: {initial_capital}
// Position size: {position_size}%
//
// Entry rule:
// {entry_comment}
//
// Exit rule:
// {exit_comment}

#region Using declarations
using System;
using NinjaTrader.Cbi;
using NinjaTrader.NinjaScript;
using NinjaTrader.NinjaScript.Indicators;
#endregion

namespace NinjaTrader.NinjaScript.Strategies
{{
    public class {class_name} : Strategy
    {{
        protected override void OnStateChange()
        {{
            if (State == State.SetDefaults)
            {{
                Description = "Starter strategy exported from Tradecraft JSON. Review generated conditions before live use.";
                Name = "{class_name}";
                Calculate = Calculate.OnBarClose;
                EntriesPerDirection = 1;
                EntryHandling = EntryHandling.AllEntries;
                IsExitOnSessionCloseStrategy = true;
                ExitOnSessionCloseSeconds = 30;
                MaximumBarsLookBack = MaximumBarsLookBack.TwoHundredFiftySix;
                StartBehavior = StartBehavior.WaitUntilFlat;
                TimeInForce = TimeInForce.Gtc;
                BarsRequiredToTrade = 200;
            }}
        }}

        protected override void OnBarUpdate()
        {{
            if (CurrentBar < BarsRequiredToTrade)
                return;

            // TODO: Translate the JSON comments above into exact NinjaScript indicator calls.
            // The MVP exporter creates a safe scaffold because pandas-ta and NinjaTrader
            // indicator naming/parameter semantics are not always one-to-one.
            bool entrySignal = false;
            bool exitSignal = false;

            if (Position.MarketPosition == MarketPosition.Flat && entrySignal)
                EnterLong("TradecraftLong");

            if (Position.MarketPosition == MarketPosition.Long && exitSignal)
                ExitLong("TradecraftExit", "TradecraftLong");
        }}
    }}
}}
"""


def rule_comment(node: dict[str, Any] | None, depth: int = 0) -> str:
    indent = "  " * depth
    if not node:
        return f"{indent}<empty>"
    if node.get("type") == "condition":
        return f"{indent}{operand_comment(node.get('left'))} {node.get('comparator')} {operand_comment(node.get('right'))}"

    operator = node.get("operator", "AND")
    children = node.get("conditions", [])
    if not children:
        return f"{indent}{operator} <empty>"
    rendered = [f"{indent}{operator}("]
    rendered.extend(rule_comment(child, depth + 1) for child in children)
    rendered.append(f"{indent})")
    return "\n// ".join(rendered)


def operand_comment(operand: dict[str, Any] | None) -> str:
    if not operand:
        return "<empty>"
    operand_type = operand.get("type")
    if operand_type == "value":
        return str(operand.get("value", 0))
    if operand_type == "price":
        timeframe = f"[{operand.get('timeframe')}]" if operand.get("timeframe") else ""
        return f"{operand.get('field', 'close')}{timeframe}"
    if operand_type == "indicator":
        params = ", ".join(f"{key}={value}" for key, value in (operand.get("params") or {}).items())
        timeframe = f"[{operand.get('timeframe')}]" if operand.get("timeframe") else ""
        field = f".{operand.get('field')}" if operand.get("field") else ""
        return f"{operand.get('name', 'indicator')}({params}){field}{timeframe}"
    return str(operand)
